### ISSUE TITLE
Error: Two records did not send to Redox this morning due to missing serialization of a Test_result_status value

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#920]
Error: Two CO records did not send to Redox this morning.

The Redox error on redoxengine website was "`Required Field Missing - Orders[].Results[].Status In Results:NewUnsolicited"`
Cause: the SimpleReport Test_result_status field was 'X', meaning "Order Cancelled"
valueset is hl70123
Normally that field is 'F' for a regular "Final" test result, sometimes its 'C'.   And now 'X', which our code does not handle.

We didn't know how to serialize the 'X', so its a null in the redox json.
Note:  The Orders[].Results[].ResultStatus is also null, 

Supported values for Orders[].Results[].Status are:
```
Final		 
Preliminary	 
Corrected	 
Canceled	 
Unavailable	 
-- These three are in Orders[].Results[].Status, but not in Orders[].ResultStatus, so we won't use them.
-- Incomplete	 
-- None Specified	 
-- Deleted

```
SupportValues for Orders[].ResultStatus are:
```
Final	      
Preliminary   
-- Not in Orders[].Results[].Status:    In Process    
Corrected     
Canceled      
Unavailable
```

So the intersection of available status values in Redox that cover both these fields is:
```
Final	      
Preliminary   
Corrected     
Canceled      
Unavailable

```
The mapping in covid-19-redox.schema looks like this:
```
  - name: test_result_status
    redoxOutputFields: ["Orders[0].ResultsStatus", "Orders[0].Results[0].Status"]
    altValues:
      - display: Corrected
        code: C
      - display: Final
        code: F

```
And the hl70123 valueset looks like this:
```
    - code: A
      display: Some, but not all, results available
    - code: C
      display: Corrected, final
    - code: F
      display: Final results
    - code: I
      display: No results available; specimen received, procedure incomplete
    - code: M
      display: Corrected, not final
    - code: N
      display: Procedure completed, results pending
    - code: O
      display: Order received; specimen not yet received
    - code: P
      display: Preliminary
    - code: R
      display: Results stored; not yet verified
    - code: S
      display: No results available; procedure scheduled, but not done
    - code: X
      display: No results available; Order canceled
    - code: Y
      display: No order on record for this test
    - code: Z
      display: No record of this patient
```

**FINALLY, HERE IS THE FIX**:  So based on those codes I'm changing the altValues so it looks like this:

```
  - name: test_result_status
    redoxOutputFields: ["Orders[0].ResultsStatus", "Orders[0].Results[0].Status"]
    altValues:
      - display: Corrected
        code: C
      - display: Final
        code: F
      - display: Canceled
        code: X
      - display: Preliminary
        code: A
      - display: Unavailable
        code: I
      - display: Corrected
        code: M
      - display: Preliminary
        code: N
      - display: Preliminary
        code: O
      - display: Preliminary
        code: P
      - display: Preliminary
        code: R
      - display: Unavailable
        code: S
      - display: Unavailable
        code: Y
      - display: Unavailable
        code: Z

```
